apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-restapi-dep-v2
  name: sbk8s-dep-v2
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: hello-world-restapi-pod-v2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world-restapi-pod-v2
    spec:
      containers:
        - image: sendebojyoti/springbootkk8s01:0.0.2-SNAPSHOT
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          name: hello-world-restapi-con-v2
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

