apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springbootkk8s01
  name: springbootkk8s01
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: springbootkk8s01
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: springbootkk8s01
    spec:
      containers:
      - image: sendebojyoti/springbootkk8s01:0.0.1-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: springbootkk8s01
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: springbootkk8s01
  name: springbootkk8s01
  namespace: default
spec:
  ports:
  - nodePort: 30703
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: springbootkk8s01
  sessionAffinity: None # ClientIP
  type: LoadBalancer