apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sbk8s-dep
  name: sbk8s-dep
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: sbk8s-pod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sbk8s-pod
    spec:
      containers:
      - image: sendebojyoti/springbootkk8s01:0.0.2-SNAPSHOT
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        name: sbk8s-con
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: sbk8s-svc
  name: sbk8s-svc
  namespace: default
spec:
  selector:
    app: sbk8s-pod
  sessionAffinity: None
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
