apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-rest-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-world-rest-api-ingress
                port:
                  number: 8080